name: Test ros_azure_iothub
on:
  pull_request:
  push:
    branches:
      - seanyen**

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: seanyen/setup-ros@seanyen/windows
      with:
        required-ros-distributions: melodic
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: ros1_rosbag_storage_vendor rosbag2_bag_v2_plugins
        source-ros-binary-installation: melodic
